version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: OrderDishesRestaurant
    ports:
      - "54320:5432"
  fams:
    image: phucloc418/orderdish
    ports:
      - "8081:8080"
    environment:
     DB_URL: jdbc:postgresql://postgres:5432/OrderDishesRestaurant
     DB_USERNAME: postgres
     DB_PASSWORD: sa
     DB_DRIVER: org.postgresql.Driver